//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedbackrecord
    {
        public System.Guid Feedbackid { get; set; }
        public System.Guid Memberid { get; set; }
        public byte Ishdz { get; set; }
        public string Hdzaccount { get; set; }
        public int Total { get; set; }
        public int Money { get; set; }
        public int Remains { get; set; }
        public int Cash { get; set; }
        public string Bankaccount { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public System.DateTime Updatedate { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
